# fig2c_ora_fig_final.R
# ============================================================================
# Purpose: Create ORA bar‑plots for Dys‑CIM and Fun‑CIM using pre‑computed
#          ORA result CSV files.
# Inputs:  oncoimmunology_paper/Results/fig2c_DysCIM_ORA.csv
#          oncoimmunology_paper/Results/fig2c_FunCIM_ORA.csv
# Outputs: PNG plots saved to oncoimmunology_paper/Results/
# Author: Adapted by GitHub Copilot
# ============================================================================

library(data.table)
library(ggplot2)
library(stringr)
library(grid)

# ---------------------------------------------------------------------------
# Paths to the ORA result CSV files (generated by fig2c_corr_ora.R)
# ---------------------------------------------------------------------------
 dys_csv <- "oncoimmunology_paper/Results/fig2c_DysCIM_ORA.csv"
 fun_csv <- "oncoimmunology_paper/Results/fig2c_FunCIM_ORA.csv"

# Load the CSVs – they contain the standard enrichGO result table
 dys_res <- fread(dys_csv) |> as.data.frame(check.names = FALSE)
 fun_res <- fread(fun_csv) |> as.data.frame(check.names = FALSE)

# ---------------------------------------------------------------------------
# Define the GO‑BP terms the user wants to display for each trajectory
# ---------------------------------------------------------------------------
 dys_terms <- c(
   "oxidative phosphorylation",
   "mitochondrial translation",
   "mitochondrial gene expression",
   "proton motive force-driven ATP synthesis",
   "aerobic respiration",
   "nuclear division",
   "ribose phosphate biosynthetic process",
   "ribonucleoprotein complex biogenesis",
   "rRNA processing",
   "rRNA metabolic process",
   "tRNA 5'-end processing",
   "protein-RNA complex assembly",
   "protein folding",
   "regulation of mitochondrial translation",
   "protein stabilization"
 )

 fun_terms <- c(
   "leukocyte activation involved in inflammatory response",
   "cell chemotaxis",
   "cell killing",
   "cellular response to chemokine",
   "cellular response to type II interferon",
   "chemotaxis",
   "leukocyte mediated immunity",
   "leukocyte migration",
   "lymphocyte proliferation",
   "MHC class II protein complex assembly",
   "pyroptotic cell death",
   "positive regulation of T cell activation",
   "pyroptotic inflammatory response",
   "T cell mediated immunity",
   "regulation of production of molecular mediator of immune response"
 )

# ---------------------------------------------------------------------------
# Helper to build a plot from a data.frame of ORA results
# ---------------------------------------------------------------------------
 # Adjustable width for wrapping long GO term descriptions (default 20 characters)
 wrap_width <- 40

 make_ora_plot <- function(df, term_vec, set_name) {
  # Keep only rows whose Description matches the supplied terms (exact match)
  df_filt <- df[df$Description %in% term_vec, , drop = FALSE]

  if (nrow(df_filt) == 0) {
    message(set_name, " – no matching terms found in the ORA table.")
    return(NULL)
  }

  # Wrap long descriptions for better readability
  df_filt$Description <- str_wrap(df_filt$Description, width = wrap_width)
  # Order the terms by adjusted p‑value (ascending) for plotting
  # Use dplyr::arrange to sort; ensure the factor levels reflect this order.
  df_filt <- df_filt[order(df_filt$p.adjust), , drop = FALSE]
  # Preserve the order after sorting for consistent visual layout.
  # Create factor levels based on the sorted (and wrapped) descriptions.
  df_filt$Description <- factor(df_filt$Description, levels = rev(df_filt$Description))

  p <- ggplot(df_filt, aes(x = Description, y = Count)) +
    geom_col(aes(fill = p.adjust), colour = "black") +
    coord_flip() +
    labs(
      # title = paste0(set_name, " – Selected GO BP Terms"),
      x = NULL,
      y = "Gene Count",
      fill = "FDR-adjusted p"
    ) +
    scale_fill_gradient(
      low = "red",
      high = "blue",
      trans = "reverse",
      labels = scales::label_scientific(digits = 2)
    ) +
    theme_minimal(base_size = 14) +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
      axis.text.y = element_text(size = 25, colour = "black", face = "bold"),
      axis.text.x = element_text(size = 25, colour = "black", face = "bold"),
      axis.title.x = element_text(size = 25, colour = "black", face = "bold"),
      legend.text = element_text(size = 20),
      legend.title = element_text(size = 20)
    )

  # Save the plot
  plot_file <- file.path("oncoimmunology_paper/Results", paste0("fig2c_", set_name, "_ORA_plot_final.png"))
  ggsave(plot_file, plot = p, width = 14, height = 10, dpi = 300)
  message("Saved plot: ", plot_file)

  return(p)
}

# ---------------------------------------------------------------------------
# Generate plots for Dys‑CIM and Fun‑CIM
# ---------------------------------------------------------------------------
 dys_plot <- make_ora_plot(dys_res, dys_terms, "DysCIM")
 fun_plot <- make_ora_plot(fun_res, fun_terms, "FunCIM")


message("fig‑making script completed.")
