# ============================================================================
# fig2_viral_mimicry_fry.R
# ============================================================================
# Purpose:
#   Generate a heatmap of Z‑score normalized expression for the "viral mimicry"
#   gene set across CIMIC clusters (NKI_SMC cohort) and compute per‑gene
#   limma moderated‑t test p‑values.
#
#   Heatmap approach borrowed from fig2e_zscore_heatmap_fry.R.
#   Per‑gene limma statistics approach borrowed from nki_smc_figure_individual_gene_panels.R.
#
# Input:
#   oncoimmunology_paper/Datasets/NKI_SMC/nki_smc_combine_clustered_plot_df.csv
#
# Outputs:
#   - oncoimmunology_paper/Results/fig2f_viral_mimicry_heatmap.png
#   - oncoimmunology_paper/Results/viral_mimicry_limma_stats.csv
#   - (optional) per‑gene panel PNGs generated by the helper function from the
#     original individual‑gene script (not created here to keep runtime low).
#
# Dependencies: R ≥ 4.0
#   data.table, dplyr, tidyr, ggplot2, limma, stringr
# ============================================================================

library(data.table)
library(dplyr)
library(tidyr)
library(ggplot2)
library(limma)
library(stringr)

# ---------------------------------------------------------------------------
# 1. Define the viral mimicry gene set
# ---------------------------------------------------------------------------
viral_mimicry_set <- c(
  "CGAS","STING1","IFI16","AIM2","ZBP1",
  "RIGI","IFIH1","DHX58","TLR3","TLR7","TLR8","TLR9",
  "MAVS","TBK1","IRF3","IRF7","STAT1","STAT2",
  "IFIT1","IFIT2","IFIT3","OAS1","OAS2","OAS3","RNASEL",
  "MX1","MX2","ISG15","RSAD2","BST2","IFI44","IFI44L","IFI6","EIF2AK2",
  "B2M","HLA-A","HLA-B","HLA-C","TAP1","TAPBP","PSMB8","PSMB9","NLRC5",
  "CXCL9","CXCL10","CXCL11","CCL5"
)

# ---------------------------------------------------------------------------
# 2. Load data
# ---------------------------------------------------------------------------
clustered_plot_df <- data.table::fread(
  "oncoimmunology_paper/Datasets/NKI_SMC/nki_smc_combine_clustered_plot_df.csv",
  data.table = FALSE
) %>% as.data.frame()

# Ensure cluster column is present and correctly named
if ("cluster_assignments" %in% colnames(clustered_plot_df)) {
  clustered_plot_df <- clustered_plot_df %>%
    dplyr::rename(CIMIC_Cluster = cluster_assignments)
} else if (!"CIMIC_Cluster" %in% colnames(clustered_plot_df)) {
  stop("Neither 'cluster_assignments' nor 'CIMIC_Cluster' found.")
}

clustered_plot_df$CIMIC_Cluster <- as.character(clustered_plot_df$CIMIC_Cluster)
if (!all(unique(clustered_plot_df$CIMIC_Cluster) %in% c("1", "2"))) {
  stop("Unexpected CIMIC_Cluster values; expected '1' and '2'.")
}

# ---------------------------------------------------------------------------
# 3. Identify gene columns (metadata vs expression)
# ---------------------------------------------------------------------------
metadata_cols <- c(
  "sample_id", "CIMIC_Cluster", "base_id", "PACMAP1", "PACMAP2",
  "UMAP1", "UMAP2", "PC1", "PC2", "PC3", "V1"
)

gene_cols <- setdiff(colnames(clustered_plot_df), metadata_cols)

# Keep only genes that are present in the viral mimicry set
viral_genes_present <- intersect(viral_mimicry_set, gene_cols)
if (length(viral_genes_present) == 0) {
  stop("None of the viral mimicry genes were found in the dataset.")
}

# ---------------------------------------------------------------------------
# 4. Z‑score normalization (display only – not used for limma testing)
# ---------------------------------------------------------------------------
# Function to safely compute Z‑scores (returns 0 when variance is zero).
zscore_safe <- function(x) {
  s <- sd(x, na.rm = TRUE)
  m <- mean(x, na.rm = TRUE)
  if (is.na(s) || s == 0) {
    rep(0, length(x))
  } else {
    (x - m) / s
  }
}

# Compute Z‑scores for all viral‑mimicry genes. This data frame is used later
# for the program‑level boxplot.
df_z <- clustered_plot_df %>%
  dplyr::mutate(across(all_of(viral_genes_present), zscore_safe))

# ---------------------------------------------------------------------------
# 5. Prepare data for heatmap (mean Z‑score per cluster per gene)
# ---------------------------------------------------------------------------
heatmap_df <- clustered_plot_df %>%
  dplyr::select(CIMIC_Cluster, all_of(viral_genes_present)) %>%
  tidyr::pivot_longer(cols = -CIMIC_Cluster, names_to = "Gene", values_to = "ZScore") %>%
  dplyr::group_by(CIMIC_Cluster, Gene) %>%
  dplyr::summarise(mean_z = mean(ZScore, na.rm = TRUE), .groups = "drop")

# ---------------------------------------------------------------------------
# 6. Plot heatmap
# ---------------------------------------------------------------------------
p_heatmap <- ggplot(heatmap_df, aes(x = CIMIC_Cluster, y = Gene, fill = mean_z)) +
  geom_tile(color = "black", linewidth = 0.5) +
  scale_fill_gradient2(
    low = "#313695",
    mid = "white",
    high = "#A50026",
    midpoint = 0,
    name = "Mean\nΔ GE"
  ) +
  # Expand the x‑axis on the right to make room for the star annotations
  scale_x_discrete(
    labels = c("1" = "Dys\nCIM", "2" = "Fun\nCIM"),
    expand = expansion(add = c(0.5, 1.5))
  ) +
  # Remove extra padding on the y‑axis so gene labels sit closer to the tiles
  scale_y_discrete(expand = expansion(add = c(0, 0))) +
  labs(x = NULL, y = NULL, title = "Viral Mimicry Gene Set – Z‑score Heatmap (NKI_SMC)") +
  theme_void(base_size = 14) +
  theme(
    axis.text.x = element_text(face = "bold", size = 16, colour = "black"),
    axis.text.y = element_text(face = "bold", size = 14, colour = "black"),
    legend.position = "right",
    legend.title = element_text(face = "bold", size = 16),
    legend.text = element_text(face = "bold", size = 16),
    plot.title = element_text(face = "bold", size = 16, hjust = 0.5),
    # Reduce margins so the plot is less left‑biased and the legend sits closer
    # to the heatmap. Units are points.
    # Reduce left margin so the heatmap is not pushed too far to the left and
    # the legend sits closer to the plot.
    plot.margin = margin(t = 5, r = 5, b = 5, l = 5, unit = "pt"),
    legend.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt"),
    legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt"),
    # Remove any extra spacing between the plot panel and the legend box.
    legend.box.spacing = unit(0, "pt")
  ) +
  # Allow annotations placed outside the plot area to be shown
  coord_cartesian(clip = "off")

# ---------------------------------------------------------------------------
# 6b. Add significance stars to heatmap (based on limma p‑values)
# ---------------------------------------------------------------------------
# NOTE: The limma statistics (`limma_stats`) are computed later in the script.
# After they are available we merge the significance labels into the heatmap data
# and add an annotation layer that places the stars just to the right of the
# tiles (x = 2.55), matching the style of `fig2e_zscore_heatmap_fry.R`.

# This block will be executed after `limma_stats` is defined (see section 7).
add_heatmap_stars <- function() {
  # Create a table of significance symbols for each gene
  sig_labels <- limma_stats %>%
    dplyr::mutate(
      signif_label = dplyr::case_when(
        PValue <= 0.0001 ~ "****",
        PValue <= 0.001  ~ "***",
        PValue <= 0.01   ~ "**",
        PValue <= 0.05   ~ "*",
        TRUE             ~ ""
      )
    ) %>%
    dplyr::select(Gene, signif_label)

  # Merge the labels and set the gene factor order (reverse alphabetical for visual match)
  heatmap_df <<- heatmap_df %>%
    dplyr::left_join(sig_labels, by = "Gene") %>%
    dplyr::mutate(Gene = factor(Gene, levels = rev(sort(unique(Gene)))))

  # Add the significance stars using an annotate layer (as in fig2e_zscore_heatmap_fry.R).
  # This avoids any unintended geometry artifacts that can appear when using
  # geom_text with a factor index. The y‑positions are the numeric indices of the
  # Gene factor levels, and we reverse the label order to match the reversed
  # factor ordering.
  # Prepare a distinct table of genes and their significance labels
  star_df <- heatmap_df %>%
    dplyr::distinct(Gene, signif_label) %>%
    dplyr::mutate(y = seq_along(levels(heatmap_df$Gene)))

  # Use annotate (as in the reference figure) to place the stars. A slightly
  # smaller size avoids the faint horizontal line that appeared with larger
  # text, and we omit `inherit.aes` (not needed for annotate).
  p_heatmap <<- p_heatmap +
    ggplot2::annotate(
      "text",
      x = 2.55,
      y = star_df$y,
      label = rev(star_df$signif_label),
      size = 10,
      fontface = "bold",
      hjust = 0,
      colour = "black"
    )
}

# NOTE: Heatmap will be saved after significance stars are added (see later).
heatmap_path <- "oncoimmunology_paper/Results/fig2_viral_mimicry_heatmap.png"

# ---------------------------------------------------------------------------
# 7. Generate a single boxplot for the viral mimicry program (aggregated score)
# ---------------------------------------------------------------------------
# Compute a program‑level Z‑score per sample (mean Z‑score across all viral genes)
program_score_z <- df_z %>%
  dplyr::rowwise() %>%
  dplyr::mutate(ProgramScore = mean(c_across(all_of(viral_genes_present)), na.rm = TRUE)) %>%
  dplyr::ungroup() %>%
  dplyr::select(CIMIC_Cluster, ProgramScore)

# Compute a program‑level expression (mean TPM/FPKM across genes) for limma testing
# Use the original expression matrix (genes x samples) built later in the script.
# After the expression matrix is created (section 7), we will calculate the mean.

# Helper to format p‑values (same style as fig2f_2k_icd_programs_fry.R)
format_p_annotation <- function(p, prefix = "P") {
  if (is.na(p) || !is.finite(p)) {
    return(paste0(prefix, " = NA"))
  }
  if (p < 0.001) {
    return(paste0(prefix, " < 0.001"))
  }
  paste0(prefix, " = ", formatC(p, format = "f", digits = 3))
}

# After the expression matrix is defined (see later), we will perform a limma
# test on the aggregated program expression.

# Placeholder for program p‑value (will be filled later)
program_pvalue <- NA_real_

# ---------------------------------------------------------------------------
# 8. Create and save the program boxplot (after limma test is performed)
# ---------------------------------------------------------------------------
make_program_boxplot <- function() {
  # Convert the program‑level p‑value into a significance star label
  prog_sig <- dplyr::case_when(
    program_pvalue <= 0.0001 ~ "****",
    program_pvalue <= 0.001  ~ "***",
    program_pvalue <= 0.01   ~ "**",
    program_pvalue <= 0.05   ~ "*",
    TRUE                     ~ ""
  )
  # Determine y‑position for the star annotation (90% of the max score)
  star_y <- max(program_score_z$ProgramScore, na.rm = TRUE) * 0.9
  p <- ggplot(program_score_z, aes(x = CIMIC_Cluster, y = ProgramScore, fill = CIMIC_Cluster)) +
    geom_boxplot(outlier.shape = NA, colour = "black", width = 0.6, alpha = 1) +
    geom_jitter(width = 0.15, size = 3, shape = 16, colour = "black", alpha = 1) +
    annotate("text", x = 1.5, y = star_y, label = prog_sig, size = 10, fontface = "bold") +
    scale_x_discrete(labels = c("1" = "Dys\nCIM", "2" = "Fun\nCIM"), expand = expansion(add = c(0.5, 0.5))) +
    scale_fill_manual(values = c("1" = "#F8766D", "2" = "#00BFC4")) +
    labs(title = "Viral Mimicry", x = NULL, y = "Z‑score of\nProgram Activation") +
    theme_classic(base_size = 18) +
    theme(
      axis.text.x = element_text(face = "bold", size = 24, colour = "black"),
      axis.text.y = element_text(face = "bold", size = 24, colour = "black"),
      axis.title.y = element_text(face = "bold", size = 24, colour = "black"),
      plot.title = element_text(face = "bold", size = 24, hjust = 0.5),
      legend.position = "none",
      panel.grid = element_blank(),
      panel.border = element_rect(linewidth = 1, fill = NA)
    )
  out_file <- "oncoimmunology_paper/Results/fig2_viral_mimicry_program_boxplot.png"
  ggsave(out_file, plot = p, width = 6, height = 5, dpi = 300, bg = "white")
  message(sprintf("✓ Saved: %s", out_file))
}

# ---------------------------------------------------------------------------
# 7. Per‑gene limma moderated‑t test (Fun vs Dys)
# ---------------------------------------------------------------------------
# Build expression matrix (genes x samples) for the viral set
expr_matrix <- clustered_plot_df %>%
  dplyr::select(sample_id, all_of(viral_genes_present)) %>%
  tibble::column_to_rownames("sample_id") %>%
  t() %>%
  as.matrix()
storage.mode(expr_matrix) <- "numeric"

# Design matrix: cluster_factor with levels "2" (Fun) then "1" (Dys) to match
# contrast Dys - Fun later.
cluster_factor <- factor(clustered_plot_df$CIMIC_Cluster, levels = c("2", "1"))
design <- model.matrix(~ 0 + cluster_factor)
colnames(design) <- c("Fun_CIM", "Dys_CIM")

contrast <- limma::makeContrasts(Dys_CIM - Fun_CIM, levels = design)

# Fit model for all genes at once
fit <- limma::lmFit(expr_matrix, design)
fit2 <- limma::contrasts.fit(fit, contrast)
fit2 <- limma::eBayes(fit2)

# Extract statistics
top_tab <- limma::topTable(fit2, number = Inf, sort.by = "none")
# Ensure gene order matches our set
limma_stats <- data.frame(
  Gene = rownames(top_tab),
  logFC = top_tab$logFC,
  AveExpr = top_tab$AveExpr,
  t = top_tab$t,
  PValue = top_tab$P.Value,
  adj.P.Val = top_tab$adj.P.Val,
  stringsAsFactors = FALSE
)

# ---------------------------------------------------------------------------
# Compute a program‑level p‑value (aggregate across all viral mimicry genes)
# ---------------------------------------------------------------------------
# Collapse the expression matrix to a single row representing the mean expression
# of the viral mimicry gene set for each sample.
program_expr <- colMeans(expr_matrix)
program_matrix <- matrix(program_expr, nrow = 1)
rownames(program_matrix) <- "ViralMimicry"

fit_prog <- limma::lmFit(program_matrix, design)
fit_prog2 <- limma::contrasts.fit(fit_prog, contrast)
fit_prog2 <- limma::eBayes(fit_prog2)
prog_top <- limma::topTable(fit_prog2, number = 1, sort.by = "none")
program_pvalue <- prog_top$P.Value

# Save CSV
stats_path <- "oncoimmunology_paper/Results/viral_mimicry_limma_stats.csv"
write.csv(limma_stats, file = stats_path, row.names = FALSE)
message("✓ Saved limma stats: ", stats_path)

# Add significance stars to the heatmap now that limma_stats are available
add_heatmap_stars()

# Save heatmap with stars
ggsave(
  filename = heatmap_path,
  plot = p_heatmap,
  width = 8,
  height = 10,
  dpi = 300,
  bg = "white"
)
message("✓ Saved heatmap: ", heatmap_path)

# Generate the program‑level boxplot using the aggregated p‑value
make_program_boxplot()

# ---------------------------------------------------------------------------
# End of script
# ---------------------------------------------------------------------------
