# ============================================================================
# fig5g_tnbc_cl_ic30.R
# ============================================================================
# Purpose:
#   Plot IC30 (µM) differences between Fun‑CIM and Dys‑CIM cell lines in the
#   TNBC_CL_Epirubicin dataset. Uses a box‑plot style identical to
#   fig5i_5l_tnbc_cl_icd_programs_fry.R and annotates statistical significance.
#   Statistical test: Wilcoxon rank‑sum (non‑parametric) because IC30 values
#   are not assumed to be normally distributed.
#
# Outputs:
#   - Results/fig5g_tnbc_cl_ic30.png
#
# Author: Generated by GitHub Copilot
# ============================================================================

library(dplyr)
library(ggplot2)
library(rstatix)

# ---------------------------------------------------------------------------
# DATA
# ---------------------------------------------------------------------------
# Inline data as provided by the user
ic30_df <- tibble::tribble(
  ~Cell_Line,    ~CIMIC_Cluster, ~IC30,
  "BT549",      "Fun-CIM",      0.48,
  "Hs578t",     "Fun-CIM",      0.37,
  "HCC38",      "Fun-CIM",      0.15,
  "MDA-MB-157", "Fun-CIM",      0.36,
  "MDA-MB-231", "Fun-CIM",      0.54,
  "DU4475",     "Dys-CIM",      0.01,
  "HCC1395",    "Dys-CIM",      0.45,
  "HC1806",     "Dys-CIM",      0.21,
  "MDA-MB-468", "Dys-CIM",      0.07
)

# Ensure cluster is a factor with Dys first on the x-axis
ic30_df <- ic30_df %>%
  mutate(CIMIC_Cluster = factor(CIMIC_Cluster, levels = c("Dys-CIM", "Fun-CIM")))

# ---------------------------------------------------------------------------
# SHAPE MAPPING FOR CELL LINES
# ---------------------------------------------------------------------------
# Define a vector of shape codes (filled shapes) to be used for each cell line.
shape_values <- c(16, 17, 15, 18, 8, 3, 4, 7, 10)

# Create a named vector that maps each unique cell line to a shape. The names are
# the cell‑line identifiers (the "Cell_Line" column) and the values are the
# shape codes. If there are more cell lines than shapes, the shapes are recycled.
cell_line_shapes <- setNames(
  rep(shape_values, length.out = length(unique(ic30_df$Cell_Line))),
  sort(unique(ic30_df$Cell_Line))
)

# ---------------------------------------------------------------------------
# STATISTICAL TEST
# ---------------------------------------------------------------------------
# Non‑parametric Wilcoxon rank‑sum test (equivalent to Mann‑Whitney U)
stat_res <- ic30_df %>%
  wilcox_test(IC30 ~ CIMIC_Cluster) %>%
  adjust_pvalue(method = "none") %>%
  add_significance()

p_val <- stat_res$p

signif_label <- case_when(
  p_val <= 0.0001 ~ "****",
  p_val <= 0.001  ~ "***",
  p_val <= 0.01   ~ "**",
  p_val <= 0.05   ~ "*",
  p_val <  0.15   ~ sprintf("p = %.3g", p_val),
  TRUE            ~ "ns"
)

# ---------------------------------------------------------------------------
# PLOT SETTINGS
# ---------------------------------------------------------------------------
cluster_labels <- c("Dys-CIM" = "Dys-CIM", "Fun-CIM" = "Fun-CIM")
fill_colors    <- c("Dys-CIM" = "#F8766D", "Fun-CIM" = "#00BFC4")

shared_theme <- theme_classic(base_size = 18) +
  theme(
    axis.text.x   = element_text(face = "bold", size = 30, colour = "black"),
    axis.text.y   = element_text(face = "bold", size = 30, colour = "black"),
    axis.title.y  = element_text(face = "bold", size = 30, colour = "black"),
    plot.title    = element_text(face = "bold", size = 36, hjust = 0.5),
    legend.position = "right",
    panel.grid    = element_blank(),
    panel.border  = element_rect(linewidth = 1, fill = NA)
  )

# ---------------------------------------------------------------------------
# PLOT
# ---------------------------------------------------------------------------
star_y <- max(ic30_df$IC30, na.rm = TRUE) * 0.90

p <- ggplot(ic30_df, aes(x = CIMIC_Cluster, y = IC30, fill = CIMIC_Cluster)) +
  geom_boxplot(outlier.shape = NA, colour = "black", width = 0.6, alpha = 0.75) +
  geom_jitter(
    aes(shape = Cell_Line),
    width  = 0.15,
    size   = 6,
    colour = "black",
    alpha  = 0.75
  ) +
  # Use annotate to place a single significance label (avoids length mismatch warning)
  annotate("text", x = 1.5, y = star_y, label = signif_label,
           size = 10, fontface = "bold") +
  labs(
    title = "IC30",
    y = "IC30 (µM)",
    x = NULL
  ) +
  # Add the manual shape scale
  scale_shape_manual(name = "Cell line", values = cell_line_shapes) +
  scale_fill_manual(values = fill_colors) +
  scale_x_discrete(labels = cluster_labels, expand = expansion(add = c(0.5, 0.5))) +
  shared_theme

# ---------------------------------------------------------------------------
# SAVE
# ---------------------------------------------------------------------------
if (!dir.exists("oncoimmunology_paper/Results")) {
  dir.create("oncoimmunology_paper/Results", recursive = TRUE)
}

ggsave(
  "oncoimmunology_paper/Results/fig5g_tnbc_cl_ic30.png",
  plot = p,
  width = 7,
  height = 7,
  dpi = 300,
  bg = "white"
)
message("✓ Saved: Results/fig5g_tnbc_cl_ic30.png")
