# fig5_tnbc_cl_ora_figure_final.R
# ============================================================================
# Purpose: Create ORA bar‑plots for Dys‑CIM and Fun‑CIM using pre‑computed
#          ORA result CSV files specific to the TNBC‑CL dataset.
# Inputs:  oncoimmunology_paper/Results/fig5f_DysCIM_ORA.csv
#          oncoimmunology_paper/Results/fig5f_FunCIM_ORA.csv
# Outputs: PNG plots saved to oncoimmunology_paper/Results/
# Author: Adapted from fig2c2d_ora_figure_final.R
# ============================================================================

library(data.table)
library(ggplot2)
library(stringr)
library(grid)

# ---------------------------------------------------------------------------
# Paths to the ORA result CSV files (generated by fig5_tnbc_cl_hallmark_ora.R)
# ---------------------------------------------------------------------------
 dys_csv <- "oncoimmunology_paper/Results/fig5f_DysCIM_ORA.csv"
 fun_csv <- "oncoimmunology_paper/Results/fig5f_FunCIM_ORA.csv"

# Load the CSVs – they contain the standard enrichGO result table
 dys_res <- fread(dys_csv) |> as.data.frame(check.names = FALSE)
 fun_res <- fread(fun_csv) |> as.data.frame(check.names = FALSE)

# ---------------------------------------------------------------------------
# Define the GO‑BP terms the user wants to display for each trajectory
# ---------------------------------------------------------------------------
 dys_terms <- c(
   "cell cycle G1/S phase transition",
   "cellular response to chemical stress",
   "cellular response to transforming growth factor beta stimulus",
   "negative regulation of apoptotic signaling pathway",
   "positive regulation of cell growth",
   "positive regulation of cytokine production involved in inflammatory response",
   "protein folding",
   "response to transforming growth factor beta",
   "stress granule assembly",
   "protein targeting",
   "tRNA aminoacylation for protein translation",
   "ERAD pathway",
   "tumor necrosis factor-mediated signaling pathway",
   "protein polymerization",
   "response to oxidative stress"
 )

 fun_terms <- c(
   "positive regulation of defense response to virus by host",
   "response to interleukin-1",
   "monocyte chemotactic protein-1 production",
   "oxidative phosphorylation",
   "positive regulation of tumor necrosis factor production",
   "positive regulation of interleukin-12 production",
   "intrinsic apoptotic signaling pathway in response to DNA damage",
   "cellular oxidant detoxification",
   "regulation of inflammatory response to antigenic stimulus",
   "NAD+ metabolic process",
   "homologous recombination",
   "nuclear division",
   "complement activation, alternative pathway",
   "mammary gland epithelial cell proliferation",
   "cell cycle checkpoint signaling"
 )

# ---------------------------------------------------------------------------
# Helper to build a plot from a data.frame of ORA results
# ---------------------------------------------------------------------------
 # Adjustable width for wrapping long term descriptions (default 40 characters)
 wrap_width <- 50

 make_ora_plot <- function(df, term_vec, set_name) {
  # Keep only rows whose Description matches the supplied terms (exact match)
  df_filt <- df[df$Description %in% term_vec, , drop = FALSE]

  if (nrow(df_filt) == 0) {
    message(set_name, " – no matching terms found in the ORA table.")
    return(NULL)
  }

  # Wrap long descriptions for better readability
  df_filt$Description <- str_wrap(df_filt$Description, width = wrap_width)
  # Order the terms by adjusted p‑value (ascending) for plotting
  df_filt <- df_filt[order(df_filt$p.adjust), , drop = FALSE]
  # Preserve the order after sorting for consistent visual layout.
  df_filt$Description <- factor(df_filt$Description, levels = rev(df_filt$Description))

  p <- ggplot(df_filt, aes(x = Description, y = Count)) +
    geom_col(aes(fill = p.adjust), colour = "black") +
    coord_flip() +
    labs(
      # title = paste0(set_name, " – Selected GO BP Terms"),
      x = NULL,
      y = "Gene Count",
      fill = "FDR‑adjusted p"
    ) +
    scale_fill_gradient(
      low = "red",
      high = "blue",
      trans = "reverse",
      labels = scales::label_scientific(digits = 2)
    ) +
    theme_minimal(base_size = 14) +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
      axis.text.y = element_text(size = 25, colour = "black", face = "bold"),
      axis.text.x = element_text(size = 25, colour = "black", face = "bold"),
      axis.title.x = element_text(size = 25, colour = "black", face = "bold"),
      legend.text = element_text(size = 20),
      legend.title = element_text(size = 20)
    )

  # Save the plot
  plot_file <- file.path("oncoimmunology_paper/Results", paste0("fig5_tnbc_cl_", set_name, "_ORA_plot_final.png"))
  ggsave(plot_file, plot = p, width = 14, height = 12, dpi = 300)
  message("Saved plot: ", plot_file)

  return(p)
 }

# ---------------------------------------------------------------------------
# Generate plots for Dys‑CIM and Fun‑CIM
# ---------------------------------------------------------------------------
 dys_plot <- make_ora_plot(dys_res, dys_terms, "DysCIM")
 fun_plot <- make_ora_plot(fun_res, fun_terms, "FunCIM")

message("Fig5 TNBC‑CL ORA figure generation completed.")
